name: Android CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: code
    - name: Build with Gradle
      working-directory: ./code
      run: ./gradlew build
